# Mercedes-Benz Greener Manufacturing

#### Problem Statement : Reduce the time a Mercedes-Benz spends on the test bench.

Following actions should be performed:

* If for any column(s), the variance is equal to zero, then you need to remove those variable(s).


* Check for null and unique values for test and train sets.


* Apply label encoder.


* Perform dimensionality reduction.


* Predict your test_df values using XGBoost.

In [1]:
!git clone https://github.com/Simplilearn-Edu/Machine-Learning--Projects.git

Cloning into 'Machine-Learning--Projects'...
remote: Enumerating objects: 50, done.
remote: Total 50 (delta 0), reused 0 (delta 0), pack-reused 50
Unpacking objects: 100% (50/50), done.

In [15]:
import pandas as pd
import numpy as np

In [16]:
train = pd.read_csv('train.csv')
train.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [17]:
test = pd.read_csv('test.csv')
test.head()

,ID,X0,X1,X2,X3,X4,X5,X6,X8,X10,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,1,az,v,n,f,d,t,a,w,0,...,0,0,0,1,0,0,0,0,0,0
1,2,t,b,ai,a,d,b,g,y,0,...,0,0,1,0,0,0,0,0,0,0
2,3,az,v,as,f,d,a,j,j,0,...,0,0,0,1,0,0,0,0,0,0
3,4,az,l,n,f,d,z,l,n,0,...,0,0,0,1,0,0,0,0,0,0
4,5,w,s,as,c,d,y,i,m,0,...,1,0,0,0,0,0,0,0,0,0

### Apply label encoder.

In [18]:
from sklearn.preprocessing import LabelEncoder

In [20]:
for c in train.columns:
    if train[c].dtype == 'object':
        lbl = LabelEncoder()
        lbl.fit(list(train[c].values) + list(test[c].values))
        train[c] = lbl.transform(list(train[c].values))
        test[c] = lbl.transform(list(test[c].values))

In [21]:
print(f'Shape of train : {train.shape} \n\n Shape of test : {test.shape}')

Shape of train : (4209, 378)

 Shape of test : (4209, 377)

### Perform dimensionality reduction.

In [22]:
from sklearn.decomposition import PCA, FastICA

In [23]:
## PCA

pca = PCA(n_components=10,random_state=42)

pca_results_train = pca.fit_transform(train.drop(['y'],axis=1))

pca_results_test = pca.fit_transform(test)

In [24]:
# ICA

ica = FastICA(n_components=10,random_state=42)

ica_results_train = ica.fit_transform(train.drop(['y'],axis=1))

ica_results_test = ica.fit_transform(test)

### If for any column(s), the variance is equal to zero, then you need to remove those variable(s).

## Find cardinality of column